# Generated by Django 3.1.2 on 2021-05-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Articles',
        ),
    ]
