# Generated by Django 3.1.2 on 2021-05-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_auto_20210503_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='ArticleTitle',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
    ]
